### ISSUE TITLE
掲載一覧ページを作る

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/geekwomenjapan.github.io#8]
記事に取り上げてもらったらURLを並べるページを作る(紙媒体の場合は写真とって張る）

- http://www.sejuku.net/blog/906

**Comment by sd-ts1017** [comment]
取り急ぎ紹介されたのか侍エンジニア塾さんだけっぽいので、NEWSにまとめた。
そのうち作る！

**Comment by sd-ts1017** [comment]
作った
