### ISSUE TITLE
開催イベント一覧ページを作る

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/geekwomenjapan.github.io#9]
基本はdots. のページへのリンクのみでOK。
イベントレポートもdots.に集約します

**Comment by sd-ts1017** [comment]
共催イベントも追加していいかな？

**Comment by sd-ts1017** [comment]
# 過去のイベント
- NEWSにリンクを貼る

# 未来のイベント
- イベントページを作る(別のIssueを作成)
